version: '2'
services:

  myapp-rabbit:
    container_name: myapp-rabbit
    image: rabbitmq:3.6-management
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    volumes:
      - ./myapp-rabbit/definitions.json:/etc/rabbitmq/definitions.json  # Example of how you can provision a dockerized RabbitMQ server

  myapp-database:
    container_name: myapp-database
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mydbuser
      POSTGRES_DB: mydb

  external-nasty-xml-stub:
    container_name: external-nasty-xml-stub
    image: nginx:1
    ports:
      - "8089:80"
    volumes:
      - ./external-nasty-xml-stub:/usr/share/nginx/html:ro  # This is where the stubs are inserted

  myapp:
    container_name: myapp
    image: nginx:1  # Using something external which can start, replace with your actual app and configure it to connect to the rabbit, the db and the external XML service.
    ports:
      - "8080:80"
    depends_on:
      - myapp-rabbit
      - myapp-database
      - external-nasty-xml-stub
